# -*- coding: utf-8 -*-
"""6_hw.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bZWwCDbZe-_OjJrlO4BHQ8nk3YELGnq1
"""
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt

x = np.random.uniform(size=(100, 1))
epsilon = np.random.normal(scale=0.1, size=(100, 1))
y = 0.5 + 2*x + epsilon
plt.figure()
plt.scatter(x, y)
plt.show()

slope, intercept, rval, pval, stderr = stats.linregress(x.T, y.T)
print(slope, intercept, rval, pval, stderr)
plt.figure()
plt.plot(x, intercept + slope*x, c='r')
plt.scatter(x, y)
plt.show()
